# Generated by Django 4.2.7 on 2024-06-23 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arrangement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Barbershopper",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("members", models.ManyToManyField(to="main.barbershopper")),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Chorus",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.group",
                    ),
                ),
                ("size", models.IntegerField()),
                ("director", models.CharField(max_length=255)),
            ],
            bases=("main.group",),
        ),
        migrations.CreateModel(
            name="Quartet",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.group",
                    ),
                ),
            ],
            bases=("main.group",),
        ),
        migrations.CreateModel(
            name="Scoresheet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("competition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.competition")),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("music_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("performance_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("singing_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("arrangement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.arrangement")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.group")),
                ("scoresheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.scoresheet")),
            ],
        ),
        migrations.CreateModel(
            name="Judge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "specialisation",
                    models.CharField(
                        choices=[("M", "Music"), ("P", "Performance"), ("S", "Singing"), ("A", "Admin")],
                        max_length=255,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.barbershopper")),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.organization"),
        ),
        migrations.AddField(
            model_name="competition",
            name="judges",
            field=models.ManyToManyField(to="main.judge"),
        ),
        migrations.AddField(
            model_name="competition",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.organization"),
        ),
        migrations.AddField(
            model_name="arrangement",
            name="arranger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="songs_arranged", to="main.barbershopper"
            ),
        ),
        migrations.AddField(
            model_name="arrangement",
            name="composer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="songs_composed", to="main.barbershopper"
            ),
        ),
    ]
